Update assemble

diff --git a/S2iScripts/assemble b/S2iScripts/assemble
--- a/S2iScripts/assemble
+++ b/S2iScripts/assemble
@@ -14,9 +14,10 @@ fi
 echo $PWD
 
 # Binary deployment is a single war
-if [ $(ls /opt/app/src/*.jar | wc -l) -eq 1 ]; then
-  mv /opt/app/src/*.jar /opt/app/openshift-app.jar
-else
-  echo "Jar not found in /opt/app/src/"
-  exit 1
-fi
+# if [ $(ls /opt/app/src/*.jar | wc -l) -eq 1 ]; then
+#  mv /opt/app/src/*.jar /opt/app/openshift-app.jar
+# else
+#  echo "Jar not found in /opt/app/src/"
+#  exit 1
+# fi
+mvn clean package -u
